#!/bin/bash

set -x

set -eo pipefail

# If phpBB has not been installed yet, unpack it.

if [ ! -d phpbb ]; then
    tar --strip-components=1 -xjf /opt/app-root/downloads/phpbb.tar.bz2
fi

# Execute the original run script, replacing this script as current process.

exec /usr/libexec/s2i/run
